### ISSUE TITLE
Explore Docker/Kubernetes plugins

### ISSUE THREAD

**Issue by tamalsaha** [appscode-ci/cibox#6]
- [ ] https://github.com/jenkinsci/kubernetes-plugin
- [ ] https://wiki.jenkins-ci.org/display/JENKINS/Docker+Slaves+Plugin
- [ ] https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin
- [ ] https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Docker+Custom+Build+Environment+Plugin
- [ ] https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Docker+Traceability

https://docs.google.com/document/d/1h84P3TnTRLZpsOXnnakJ6QVTvV31v5D5OGln8VrfPTQ/edit#heading=h.nlg9371sep88

**Comment by TamalSaha** [comment]
GKE Auth for Kubernetes plugin:
We need to implement a TokenProducer for GKE.
 - https://github.com/fabric8io/kubernetes-client/issues/636
 - https://sourcegraph.com/github.com/jenkinsci/kubernetes-plugin@91ec6e1f2805496e74e5222849e26227110f7983/-/blob/src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java#L114:37

**Comment by TamalSaha** [comment]
Kubernetes plugin issues
 - [ ] Can't mount a secret in jnlp-slave. Secret can be used to pre-login to appscode.
 - [ ] Can't mount secret to set CA_CERT
